client_config_backend: settings
client_config:
  client_id: 967770725663-un8j5d9ih9pgedko5for767cs88f4svl.apps.googleusercontent.com
  client_secret: mTD8gVnlEsuqVFqJp6kDeGD1

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install